version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENDPOINT=https://devstudionica.ru/api
    volumes:
      - ~/ssl:/app/ssl
    ports:
      - '80:5000'
      - '443:5000'
  rendertron:
    container_name: rendertron
    build:
      context: ./rendertron
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
